name: Profile
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Profile Summary
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PROFILE_TOKEN }}
          user: Paulem79
          config_timezone: Europe/Paris
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_url: ${{ secrets.WAKATIME_URL }}
      - name: Recently starred
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stars.svg
          token: ${{ secrets.PROFILE_TOKEN }}
          user: Paulem79
          config_timezone: Europe/Paris
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3
